#!/bin/bash
GREP_ARGS=-Rn
case $1 in
    "docstrings")
	grep "📕" $GREP_ARGS
	;;
    "notes")
	grep "📝" $GREP_ARGS
	;;
    "bugs")
	grep "😢" $GREP_ARGS
	;;
    "crashes")
	grep "😭" $GREP_ARGS
	;;
    "stinks")
	grep "🤮" $GREP_ARGS
	;;
    *)
        ~/.scripts/codenotes notes
	~/.scripts/codenotes bugs
	;;
esac
